// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.15.0

package sqlc

import (
	"database/sql"
	"encoding/json"
	"time"

	"github.com/google/uuid"
)

type RegisteredPath struct {
	UserID    uuid.NullUUID
	Paths     json.RawMessage
	CreatedAt time.Time
	UpdatedAt time.Time
	DeletedAt sql.NullTime
	ID        uuid.UUID
}

type Tip struct {
	UserID    uuid.NullUUID
	Data      json.RawMessage
	CreatedAt time.Time
	UpdatedAt time.Time
	ID        string
}
