// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.15.0
// source: query.sql

package sqlc

import (
	"context"
)

const getAmountTips = `-- name: GetAmountTips :one
select count(*) from tips
`

func (q *Queries) GetAmountTips(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, getAmountTips)
	var count int64
	err := row.Scan(&count)
	return count, err
}
